CREATE TABLE scuole
(
CODICESCUOLA varchar(255) NOT NULL PRIMARY KEY,
ANNOSCOLASTICO varchar(255) NOT NULL, 
AREAGEOGRAFICA varchar(255) NOT NULL,
REGIONE varchar(255) NOT NULL,
PROVINCIA varchar(255) NOT NULL,
CODICEISTITUTORIFERIMENTO varchar(255) NOT NULL,
DENOMINAZIONEISTITUTORIFERIMENTO varchar(255) NOT NULL,
DENOMINAZIONESCUOLA varchar(255) NOT NULL,
INDIRIZZOSCUOLA varchar(255) NOT NULL,
CAPSCUOLA varchar(255) NOT NULL,
CODICECOMUNESCUOLA varchar(255) NOT NULL,
DESCRIZIONECOMUNE varchar(255) NOT NULL,
DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA varchar(255) NOT NULL,
INDIRIZZOEMAILSCUOLA varchar(255) NOT NULL,
SITOWEBSCUOLA varchar(255) NOT NULL,
INDIRIZZOPECSCUOLA varchar(255) NOT NULL,
DESCRIZIONECARATTERISTICASCUOLA varchar(255) NOT NULL,
INDICAZIONESEDEDIRETTIVO varchar(255) NOT NULL,
INDICAZIONESEDEOMNICOMPRENSIVO varchar(255) NOT NULL
)
